# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-10 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='links',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='movieinfo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='moviesmapped',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='normalisedcontentbasedfilteringdata',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='normalisedcontentbasedfilteringmap',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='normalisedcontentbasedfilteringsimilarity',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ratings',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='simplecollaborativefilteringitemrecommendation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='simplecollaborativefilteringsimilaruser',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='simplecollaborativefilteringuserrecommendation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='simplecontentbasedfiltering',
            options={'managed': True},
        ),
    ]
